name: dotnet / Validate
on:
  workflow_call:
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_ARGUMENTS: --nologo -c ${{ matrix.configuration }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dotnet
      uses: actions/setup-dotnet@v1
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore $DOTNET_ARGUMENTS
    - name: Test
      run: dotnet test --no-build $DOTNET_ARGUMENTS
    - name: Publish
      run: dotnet publish --no-build $DOTNET_ARGUMENTS
    - name: Pack
      run: dotnet pack --no-build $DOTNET_ARGUMENTS
