name: dotnet / Validate
on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: ubuntu-latest
      solution_file:
        required: false
        type: string
        default: ''
      dotnet_version:
        required: false
        type: string
        default: ''
      pack:
        required: false
        type: boolean
        default: true
    secrets:
      token:
        required: false
jobs:
  validate:
    name: Validate
    runs-on: ${{ inputs.os }}
    strategy:
      matrix:
        configuration: [Debug, Release]
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_ARGUMENTS: --nologo -c ${{ matrix.configuration }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.token || github.token }}
    - name: Install dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet_version }}
    - name: Restore
      run: dotnet restore ${{ inputs.solution_file }}
    - name: Build
      run: dotnet build ${{ inputs.solution_file }} --no-restore $DOTNET_ARGUMENTS
    - name: Test
      run: dotnet test ${{ inputs.solution_file }} --no-build $DOTNET_ARGUMENTS
    - name: Pack
      if: ${{ inputs.pack }}
      run: dotnet pack ${{ inputs.solution_file }} --no-build $DOTNET_ARGUMENTS
