name: Installer / Validate
on:
  workflow_call:
    inputs:
      solution_file:
        required: true
        type: string
      dotnet_version:
        required: false
        type: string
        default: ''
jobs:
  validate:
    name: Validate
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Install dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet_version }}
    - name: Restore
      run: msbuild ${{ inputs.solution_file }} -t:Restore -p:Configuration=${{ matrix.configuration }} -v:minimal -nologo
    - name: Build
      run: msbuild ${{ inputs.solution_file }} -t:Build -p:Configuration=${{ matrix.configuration }} -v:minimal -nologo
