name: Installer / Validate
on:
  workflow_call:
    inputs:
      solution_file:
        required: true
        type: string
      installer_project_file:
        required: true
        type: string
      installer_configuration_suffix:
        required: false
        type: string
        default: ''
      dotnet_version:
        required: false
        type: string
        default: ''
    secrets:
      token:
        required: false
defaults:
  run:
    shell: bash
jobs:
  validate:
    name: Validate
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_ARGUMENTS: --nologo -c ${{ matrix.configuration }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.token || github.token }}
    - name: Setup DevEnv
      uses: seanmiddleditch/gha-setup-vsdevenv@v4
      id: devenv
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet_version }}
    - name: Restore
      run: dotnet restore ${{ inputs.solution_file }}
    - name: Build
      run: dotnet build ${{ inputs.solution_file }} --no-restore $DOTNET_ARGUMENTS
    - name: Disable Out of Process Building
      # Required to Build VS Installer Projects
      run: DisableOutOfProcBuild.exe
      working-directory: ${{ steps.devenv.outputs.install_path }}\Common7\IDE\CommonExtensions\Microsoft\VSI\DisableOutOfProcBuild
    - name: Build Installer
      shell: cmd
      # Takes a long time: https://github.com/actions/runner-images/issues/5301
      # Time optimization with /updateconfiguration ? : https://github.com/actions/runner-images/issues/128
      run: |
        "${{ steps.devenv.outputs.install_path }}\Common7\IDE\devenv.com" ${{ inputs.solution_file }} /Build ${{ matrix.configuration }} /Project ${{ inputs.installer_project_file }} /ProjectConfig ${{ matrix.configuration }}${{ inputs.installer_configuration_suffix }}
    - name: Test
      run: dotnet test ${{ inputs.solution_file }} --no-build $DOTNET_ARGUMENTS
