name: Installer / Validate
on:
  workflow_call:
    inputs:
      core_solution_file:
        required: true
        type: string
      installer_solution_file:
        required: true
        type: string
      dotnet_version:
        required: false
        type: string
        default: ''
jobs:
  validate:
    name: Validate
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install MSBuild
      uses: microsoft/setup-msbuild@v1
      id: msbuild
    - name: Install dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet_version }}
    - name: Restore
      run: dotnet restore ${{ inputs.core_solution_file }}
    - name: Build
      shell: cmd
      # Takes a long time: https://github.com/actions/runner-images/issues/5301
      # Time optimization with /updateconfiguration ? : https://github.com/actions/runner-images/issues/128
      run: |
        "${{ steps.msbuild.outputs.msbuildPath }}\..\..\..\Common7\IDE\devenv.com" ${{ inputs.installer_solution_file }} /Build ${{ matrix.configuration }}
    - name: Test
      run: dotnet test ${{ inputs.core_solution_file }} -c ${{ matrix.configuration }} --nologo 
