name: VSIX / Validate
# Inspired by: https://cezarypiatek.github.io/post/develop-vsextension-with-github-actions/
on:
  workflow_call:
    inputs:
      solution_file:
        required: true
        type: string
      dotnet_version:
        required: false
        type: string
        default: ''
    secrets:
      token:
        required: false
defaults:
  run:
    shell: bash
jobs:
  validate:
    name: Validate
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.token || github.token }}
    - name: Install MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Install dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet_version }}
    - name: Restore
      run: dotnet restore ${{ inputs.solution_file }}
    - name: Build
      run: msbuild ${{ inputs.solution_file }} -t:Build -p:Configuration=${{ matrix.configuration }} -v:minimal -nologo
      env: 
        DeployExtension: False
    - name: Test
      run: dotnet test ${{ inputs.solution_file }} -c ${{ matrix.configuration }} --nologo 
