name: VSIX / Validate
# Inspired by: https://cezarypiatek.github.io/post/develop-vsextension-with-github-actions/
on:
  workflow_call:
    inputs:
      solution_file:
        required: true
        type: string
jobs:
  validate:
    name: Validate
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_ARGUMENTS: --nologo -c ${{ matrix.configuration }}
      MSBUILD_ARGUMENTS: /nologo /v:minimal /p:Configuration=${{ matrix.configuration }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Install dotnet
      uses: actions/setup-dotnet@v1
    - name: Restore
      run: dotnet restore ${{ inputs.solution_file }}
    - name: Build
      run: msbuild ${{ inputs.solution_file }} /t:Build $MSBUILD_ARGUMENTS
      env: 
        DeployExtension: False
    - name: Test
      run: dotnet test ${{ inputs.solution_file }} --no-build $DOTNET_ARGUMENTS
